"""New Migration

Revision ID: 509fb7f3e8d8
Revises: 0702d58a0097
Create Date: 2024-07-02 10:47:47.771181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '509fb7f3e8d8'
down_revision: Union[str, None] = '0702d58a0097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shorts',
    sa.Column('short_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('publish_date', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('actual_content_link', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('upvote', sa.Integer(), nullable=True),
    sa.Column('downvote', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('short_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shorts')
    # ### end Alembic commands ###
